<?php

namespace App\Http\Controllers;

use App\Services\TicketService;
use App\Ticket;
use App\TicketComment;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class TicketCommentController extends Controller
{
    protected $ticketService;
    public function __construct(TicketService $ticketService)
    {
        $this->ticketService = $ticketService;
        $this->middleware('auth');
    }

    public function store(Request $request)
    {
        // validate the uploaded file
        $request->validate([
            'comment' => 'required|string',
            'ticket_id' => 'required'
        ]);
        $data = $request->all();
        $data['comment_for'] = 2;
        $data['client_id'] = Auth::user()->id;
        $clientIdOfTicket = Ticket::find($request->ticket_id)->client_id;
        if ($clientIdOfTicket != Auth::user()->id){
            return redirect()->back()->with('error','Something went wrong');
        }
        $comment = TicketComment::create($data);
        if (isset($comment->id)){
            $message = 'A new Comment has been generated by Customer -'.Auth::user()->name.' from My Easytrax.

Client Name : '.Auth::user()->name.'.
User ID : '.Auth::user()->id.'
Customer Category : '.Auth::user()->category.'
Contact No : '.Auth::user()->work_phone.'
Email : '.Auth::user()->email.'

Ticket ID: '.$comment->ticket_id.'

Comment Creation Date & Time : '.Carbon::parse($comment->created_at)->toDayDateTimeString().'
Comment Body : '.$comment->comment.'

Link : https://crm.easytrax.com.bd/tickets/'.$comment->ticket_id;

            $this->ticketService->sendTelegramNotification($message);
            return redirect()->back()->with('success','Comment created successfully');
        }
        return redirect()->back()->with('error','Something went wrong');
    }
}
